# Generated by Django 5.2.7 on 2025-12-19 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rzp_order_id', models.SlugField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=25)),
                ('amount', models.FloatField()),
                ('rzp_payment_id', models.SlugField(blank=True, null=True)),
                ('rzp_payment_signature', models.TextField(blank=True, null=True)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscriptions')),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
