# Generated by Django 5.2.7 on 2025-12-19 05:37

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('devices', multiselectfield.db.fields.MultiSelectField(choices=[('All Devices', 'All Devices'), ('Phone', 'Phone'), ('Tablet', 'Tablet'), ('TV', 'TV'), ('Laptop', 'Laptop')], max_length=34)),
                ('quality', models.CharField(choices=[('480p', '480p'), ('Upto 1080p', 'Upto 1080p'), ('Upto 4k', 'Upto 4k')], max_length=30)),
                ('no_of_screens', models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4')])),
                ('download_devices', models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4')])),
            ],
            options={
                'verbose_name': 'Subscription Plans',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplans')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscription',
            },
        ),
    ]
